# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: cyan

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'Xiaoyu_Y3'
  analytics:
    google_analytics: 'google-site-verification=MwFwwP5wxXZtYSDMn0_5lF55BgiTeM_CaYZV2Y0LUf8'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '<meta name="google-site-verification" content="0xYWX84_0ZafEk-pra21kfTi4XzItNnwtefuvcvdY0M" />'
    bing: ""
    baidu: ""
    yandex: ""
    pinterest: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Xiaoyu Ye"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
